import VocanManagerContainer from "../VocabManagerContainer";
import {
  fetchVocabDeck,
  addWordToDeck,
  deleteWordFromDeck,
  deleteAllWordsFromDeck,
  autoGenerateDeckWords,
} from "../../../../api/servers/vocabDeckApi";

const ManageVocabsInVocabDeck = () => {
  return (
    <VocanManagerContainer
      fetchApi={fetchVocabDeck}
      addApi={addWordToDeck}
      deleteApi={deleteWordFromDeck}
      clearApi={deleteAllWordsFromDeck}
      onAutoGenerate={autoGenerateDeckWords}
      title="VOCABULARY DECK"
    />
  );
};

export default ManageVocabsInVocabDeck;
