import { BookOpen, Sparkles, ChevronRight } from "lucide-react";
import { useState } from "react";

const VocabHeader = ({ contentInfo, onAutoGenerate }) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleAutoGenerateDeckWords = async () => {
    setIsGenerating(true);
    await onAutoGenerate();
    setIsGenerating(false);
  };

  return (
    <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 sm:gap-3 md:gap-4 mb-4 sm:mb-5 md:mb-6">
      {/* Left Section */}
      <div className="flex items-start gap-3 md:gap-4 flex-1 min-w-0">
        <div className="p-2.5 sm:p-3 md:p-4 bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl md:rounded-2xl shadow-lg flex-shrink-0">
          <BookOpen className="w-6 h-6 sm:w-7 sm:h-7 md:w-8 md:h-8 text-white" />
        </div>
        <div className="flex-1 min-w-0">
          <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-gray-900 dark:text-gray-100 mb-1 sm:mb-1.5 md:mb-2 break-words">
            Manage Vocabularies
          </h1>
          {contentInfo && (
            <div className="flex flex-wrap items-center gap-2 md:gap-3 text-xs sm:text-sm text-gray-600 dark:text-gray-400">
              <span className="px-2 sm:px-2.5 md:px-3 py-0.5 sm:py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400 rounded-full font-medium whitespace-nowrap">
                {contentInfo.type}
              </span>
              <ChevronRight className="w-3 h-3 sm:w-3.5 sm:h-3.5 md:w-4 md:h-4 flex-shrink-0 hidden xs:block" />
              <span className="font-medium text-gray-900 dark:text-gray-100 break-words line-clamp-2">
                {contentInfo.title}
              </span>
            </div>
          )}
        </div>
      </div>

      {/* Right Section - Auto Generate Button */}
      {onAutoGenerate && (
        <div className="flex items-center gap-3 flex-shrink-0">
          <button
            onClick={handleAutoGenerateDeckWords}
            disabled={isGenerating}
            className={`w-full sm:w-auto px-4 sm:px-5 py-2.5 sm:py-3 rounded-lg sm:rounded-xl font-medium flex items-center justify-center gap-2 transition-all text-sm sm:text-base ${
              isGenerating
                ? "bg-blue-600/70 text-white cursor-not-allowed"
                : "bg-gradient-to-r from-blue-600 to-blue-700 text-white hover:shadow-lg hover:scale-105"
            }`}
          >
            <Sparkles className="w-4 h-4 sm:w-5 sm:h-5" />
            <span>{isGenerating ? "Generating..." : "Auto Generate"}</span>
          </button>
        </div>
      )}
    </div>
  );
};

export default VocabHeader;
