import { serverInstance } from "../../config/axios";

export const fetchVocabDecks = async (
  page = 1,
  size = 10,
  sortBy = "id",
  direction = "desc",
  keyword = ""
) => {
  try {
    const response = await serverInstance.get("/vocab-deck", {
      params: { page, size, sortBy, direction, keyword },
    });
    return response.data;
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const fetchVocabDecksByGroup = async (
  groupId,
  page = 1,
  size = 10,
  sortBy = "id",
  direction = "desc",
  keyword = ""
) => {
  try {
    const response = await serverInstance.get(`/vocab-deck/group/${groupId}`, {
      params: { page, size, sortBy, direction, keyword },
    });
    return response.data;
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const fetchVocabDeck = async (id) => {
  try {
    const response = await serverInstance.get(`/vocab-deck/${id}`);
    return response.data;
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const createVocabDeck = async (data) => {
  try {
    await serverInstance.post("/vocab-deck", data);
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const addWordToDeck = async (deckId, wordId) => {
  try {
    await serverInstance.post(`/vocab-deck/${deckId}/word/${wordId}`);
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const autoGenerateDeckWords = async (deckId) => {
  try {
    await serverInstance.post(`/vocab-deck/${deckId}`);
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const deleteWordFromDeck = async (deckId, wordId) => {
  try {
    await serverInstance.delete(`/vocab-deck/${deckId}/word/${wordId}`);
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const deleteAllWordsFromDeck = async (deckId) => {
  try {
    await serverInstance.delete(`/vocab-deck/${deckId}/word`);
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const updateVocabDeck = async (id, data) => {
  try {
    await serverInstance.put(`/vocab-deck/${id}`, data);
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const toggleVocabDeck = async (id) => {
  try {
    await serverInstance.patch(`/vocab-deck/${id}/enabled`);
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};

export const deleteVocabDeck = async (id) => {
  try {
    await serverInstance.delete(`/vocab-deck/${id}`);
  } catch (err) {
    console.error("Error:", err);
    throw err;
  }
};
